services:
  info-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'info-service:1.0.0'
    container_name: info-service
    ports:
      - 8184:8184
    restart: always
    volumes:
      - '/usr/local/servers/info-service/logs:/app/info-service/logs'
    environment:
      PORT: 8184
      LOG_LEVEL: 'info'
      ENVIRONMENT: 'PRODUCTION'
      SCHEMA_NAME: info_service
      # DB_SETTINGS
      DB_USER: gdzapp
      DB_HOST: postgresql
      DB_DATABASE: host
      DB_PASSWORD: password
      DB_PORT: 5432

    networks:
      - gdz_network

networks:
  gdz_network:
    external: true
