FROM node:20.12-alpine3.18

# Додано залежності
RUN apk update && apk add --no-cache git bash

WORKDIR /app/info-service

RUN git clone -b main https://github.com/oshuster/info-service.git .

RUN npm install

EXPOSE 8080

CMD ["npm", "start"]